# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b97303a3d94df80a3ca72eaf5866a7edcb19cae5be60deaaddc3e4585821497ae9a6f8019703e35846a25ebcd48b57bc04b6f54a6cfd6c128f0b203c8a70590

test:
  secret_key_base: fb9632f19304cf81d83851ec39ce5b93eef0bae4b6cce4bd7518e257b715a2a915553d22d982c0d367f6b73349fdf30845d8bf1d0c3e2ea7a5b2c291b2b855e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
